### PR TITLE
Add patch to oslodb for removed table.count

### PR DESCRIPTION
**Pull request by CaselIT**
@zzzeek

### CODE REVIEW

**Comment by zzzeek** [comment]
OK I'd have to propose this to them, is this for future 2.0 removal of table.count() or is that one of the < 1.1 things we're removing?

**Comment by CaselIT** [comment]
One of the <1.1 we are removing

**Comment by zzzeek** [comment]
OK, so I have to merge this + apply to CI plus propose up to openstack.   will try to get to this tomorrow.

**Comment by CaselIT** [comment]
Ok, thanks. Once it's merged we need to recheck this https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1833

**Comment by zzzeek** [comment]
found the guy who used that awful table.count() function

https://github.com/openstack/oslo.db/commit/78fd290a

**Comment by CaselIT** [comment]
Ahah, he's the worst 😄

**Comment by CaselIT** [comment]
The patch works: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1833#message-0b71f92b_5b3f05d5

**Pull request merged**
